name: World Population System

on: push

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Package and Run Tests
        run: |
          mvn clean test package -DskipTests
          docker-compose up --abort-on-container-exit