name: A workflow for World Population System
on: push

jobs:
  build:
    name: World Population System
    runs-on: ubuntu-20.04
    env:
      MYSQL_ROOT_HOST: 172.20.0.1 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn package
      - name: Run docker compose
        run: docker-compose up --abort-on-container-exit
